In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn.linear_model import LogisticRegression
import warnings 
warnings.filterwarnings('ignore')

In [2]:
train=pd.read_csv('train_hr.csv')
train.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  8              1            0                  49   
1                  4              0            0                  60   
2                  7              0            0                  50   
3                 10              0            0                  50   
4                  2              0            0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0

In [3]:
train.shape

(54808, 14)

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   employee_id           54808 non-null  int64  
 1   department            54808 non-null  object 
 2   region                54808 non-null  object 
 3   education             52399 non-null  object 
 4   gender                54808 non-null  object 
 5   recruitment_channel   54808 non-null  object 
 6   no_of_trainings       54808 non-null  int64  
 7   age                   54808 non-null  int64  
 8   previous_year_rating  50684 non-null  float64
 9   length_of_service     54808 non-null  int64  
 10  KPIs_met >80%         54808 non-null  int64  
 11  awards_won?           54808 non-null  int64  
 12  avg_training_score    54808 non-null  int64  
 13  is_promoted           54808 non-null  int64  
dtypes: float64(1), int64(8), object(5)
memory usage: 5.9+ MB


In [5]:
train.describe()

employee_id  no_of_trainings           age  previous_year_rating  \
count  54808.000000     54808.000000  54808.000000          50684.000000   
mean   39195.830627         1.253011     34.803915              3.329256   
std    22586.581449         0.609264      7.660169              1.259993   
min        1.000000         1.000000     20.000000              1.000000   
25%    19669.750000         1.000000     29.000000              3.000000   
50%    39225.500000         1.000000     33.000000              3.000000   
75%    58730.500000         1.000000     39.000000              4.000000   
max    78298.000000        10.000000     60.000000              5.000000   

       length_of_service  KPIs_met >80%   awards_won?  avg_training_score  \
count       54808.000000   54808.000000  54808.000000        54808.000000   
mean            5.865512       0.351974      0.023172           63.386750   
std             4.265094       0.477590      0.150450           13.371559   
min             1.000000       0.000000      0.000000           39.000000   
25%             3.000000       0.000000      0.000000           51.000000   
50%             5.000000       0.000000      0.000000           60.000000   
75%             7.000000       1.000000      0.000000           76.000000   
max            37.000000       1.000000      1.000000           99.000000   

        is_promoted  
count  54808.000000  
mean       0.085170  
std        0.279137  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000

In [6]:
train.isna().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [7]:
train.previous_year_rating.fillna(0,inplace=True)

In [8]:
train.education.fillna(train.education.mode()[0],inplace=True)

In [9]:
train.isna().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   employee_id           54808 non-null  int64  
 1   department            54808 non-null  object 
 2   region                54808 non-null  object 
 3   education             54808 non-null  object 
 4   gender                54808 non-null  object 
 5   recruitment_channel   54808 non-null  object 
 6   no_of_trainings       54808 non-null  int64  
 7   age                   54808 non-null  int64  
 8   previous_year_rating  54808 non-null  float64
 9   length_of_service     54808 non-null  int64  
 10  KPIs_met >80%         54808 non-null  int64  
 11  awards_won?           54808 non-null  int64  
 12  avg_training_score    54808 non-null  int64  
 13  is_promoted           54808 non-null  int64  
dtypes: float64(1), int64(8), object(5)
memory usage: 5.9+ MB


In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in train.columns:
    train[i]=le.fit_transform(train[i])

In [12]:
train

employee_id  department  region  education  gender  \
0            45805           7      31          2       0   
1            45593           4      14          0       1   
2             5247           7      10          0       1   
3             1772           7      15          0       1   
4            34270           8      18          0       1   
...            ...         ...     ...        ...     ...   
54803         2111           8       5          0       1   
54804        52191           4      19          2       0   
54805         9695           0       0          0       1   
54806         9475           7      33          0       1   
54807        36062           2      14          0       1   

       recruitment_channel  no_of_trainings  age  previous_year_rating  \
0                        2                0   15                     5   
1                        0                0   10                     5   
2                        2                0   14                     3   
3                        0                1   19                     1   
4                        0                0   25                     3   
...                    ...              ...  ...                   ...   
54803                    2                0   28                     3   
54804                    0                0   17                     2   
54805                    0                0    7                     5   
54806                    2                0    9                     1   
54807                    0                0    7                     1   

       length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                      7              1            0                  10   
1                      3              0            0                  21   
2                      6              0            0                  11   
3                      9              0            0                  11   
4                      1              0            0                  34   
...                  ...            ...          ...                 ...   
54803                 16              0            0                  39   
54804                  5              0            0                  17   
54805                  2              1            0                  40   
54806                  1              0            0                   6   
54807                  4              0            0                  10   

       is_promoted  
0                0  
1                0  
2                0  
3                0  
4                0  
...            ...  
54803            0  
54804            0  
54805            0  
54806            0  
54807            0  

[54808 rows x 14 columns]

In [13]:
train.columns

Index(['employee_id', 'department', 'region', 'education', 'gender',
       'recruitment_channel', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'KPIs_met >80%', 'awards_won?',
       'avg_training_score', 'is_promoted'],
      dtype='object')

In [14]:
train.drop(['employee_id','region','recruitment_channel'],axis=1,inplace=True)

In [15]:
X=train.values[:,0:-1]
Y=train['is_promoted']

In [16]:
print(X.shape)
print(Y.shape)

(54808, 10)
(54808,)


In [17]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
rfe=RFE(model,n_features_to_select=10)
rfe.fit(X,Y)
print(rfe.support_)

[ True  True  True  True  True  True  True  True  True  True]


In [18]:
print(list(zip(train.columns,rfe.support_)))

[('department', True), ('education', True), ('gender', True), ('no_of_trainings', True), ('age', True), ('previous_year_rating', True), ('length_of_service', True), ('KPIs_met >80%', True), ('awards_won?', True), ('avg_training_score', True)]


In [19]:
X.shape

(54808, 10)

In [20]:
scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)
X

array([[ 0.80893285,  1.61975831, -1.53622276, ...,  1.35687789,
        -0.15401776, -1.07593145],
       [-0.38818322, -0.62883817,  0.65094726, ..., -0.73698599,
        -0.15401776, -0.25328242],
       [ 0.80893285, -0.62883817,  0.65094726, ..., -0.73698599,
        -0.15401776, -1.00114517],
       ...,
       [-1.98433798, -0.62883817,  0.65094726, ...,  1.35687789,
        -0.15401776,  1.1676568 ],
       [ 0.80893285, -0.62883817,  0.65094726, ..., -0.73698599,
        -0.15401776, -1.37507655],
       [-1.1862606 , -0.62883817,  0.65094726, ..., -0.73698599,
        -0.15401776, -1.07593145]])

In [21]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

In [22]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(38365, 10)
(38365,)
(16443, 10)
(16443,)


In [23]:
model.fit(X_train,Y_train)
print(model.intercept_)
print(model.coef_)

[-2.8763648]
[[ 0.18516349  0.1190673   0.00849203 -0.10080482 -0.18448245  0.312476
   0.08044907  0.6571253   0.29277324  0.6323734 ]]


In [24]:
Y_pred=model.predict(X_test)
Y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [25]:
Y_pred_prob=model.predict_proba(X_test)
Y_pred_prob

array([[0.98649815, 0.01350185],
       [0.9894053 , 0.0105947 ],
       [0.96410674, 0.03589326],
       ...,
       [0.98770967, 0.01229033],
       [0.91821387, 0.08178613],
       [0.94593302, 0.05406698]])

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[14998    66]
 [ 1285    94]]
Classification report: 
              precision    recall  f1-score   support

           0       0.92      1.00      0.96     15064
           1       0.59      0.07      0.12      1379

    accuracy                           0.92     16443
   macro avg       0.75      0.53      0.54     16443
weighted avg       0.89      0.92      0.89     16443

Accuracy of the model:  0.9178373776074925


In [27]:
for a in np.arange(0.4,0.61,0.01):  #0.4 to 0.6
    predict_mine = np.where(Y_pred_prob[:,1] > a, 1, 0)  #where lets us write conditional statement
    cfm=confusion_matrix(Y_test, predict_mine)
    total_err=cfm[0,1]+cfm[1,0]
    print("Errors at threshold ", a, ":",total_err, " , type 2 error :", 
          cfm[1,0]," , type 1 error:", cfm[0,1])

Errors at threshold  0.4 : 1376  , type 2 error : 1214  , type 1 error: 162
Errors at threshold  0.41000000000000003 : 1353  , type 2 error : 1222  , type 1 error: 131
Errors at threshold  0.42000000000000004 : 1348  , type 2 error : 1232  , type 1 error: 116
Errors at threshold  0.43000000000000005 : 1344  , type 2 error : 1240  , type 1 error: 104
Errors at threshold  0.44000000000000006 : 1346  , type 2 error : 1249  , type 1 error: 97
Errors at threshold  0.45000000000000007 : 1345  , type 2 error : 1254  , type 1 error: 91
Errors at threshold  0.4600000000000001 : 1347  , type 2 error : 1262  , type 1 error: 85
Errors at threshold  0.4700000000000001 : 1345  , type 2 error : 1266  , type 1 error: 79
Errors at threshold  0.4800000000000001 : 1346  , type 2 error : 1273  , type 1 error: 73
Errors at threshold  0.4900000000000001 : 1350  , type 2 error : 1280  , type 1 error: 70
Errors at threshold  0.5000000000000001 : 1351  , type 2 error : 1285  , type 1 error: 66
Errors at thresh

In [28]:
y_pred_class=[]
for value in Y_pred_prob[:,1]:
    if value>0.4:
        y_pred_class.append(1)
    else:
        y_pred_class.append(0)

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,y_pred_class)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,y_pred_class))
 
acc=accuracy_score(Y_test, y_pred_class)
print("Accuracy of the model: ",acc)

[[14902   162]
 [ 1214   165]]
Classification report: 
              precision    recall  f1-score   support

           0       0.92      0.99      0.96     15064
           1       0.50      0.12      0.19      1379

    accuracy                           0.92     16443
   macro avg       0.71      0.55      0.57     16443
weighted avg       0.89      0.92      0.89     16443

Accuracy of the model:  0.9163169737882382


In [30]:
model_DT=DecisionTreeClassifier(random_state=10,
                                criterion='gini',
                               splitter="best",
                               min_samples_leaf=3,
                               min_samples_split=5,
                               max_depth=10,
                               max_leaf_nodes=100)
model_DT.fit(X_train,Y_train)
Y_pred=model_DT.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0),

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[14990    74]
 [ 1019   360]]
Classification report: 
              precision    recall  f1-score   support

           0       0.94      1.00      0.96     15064
           1       0.83      0.26      0.40      1379

    accuracy                           0.93     16443
   macro avg       0.88      0.63      0.68     16443
weighted avg       0.93      0.93      0.92     16443

Accuracy of the model:  0.9335279450221979


In [32]:
test=pd.read_csv("test_hr.csv")
test_copy=test.copy()
test.shape

(23490, 13)

In [33]:
test.drop(['employee_id','region','recruitment_channel'],axis=1,inplace=True)

In [34]:
test.shape

(23490, 10)

In [35]:
test.isna().sum()

department                 0
education               1034
gender                     0
no_of_trainings            0
age                        0
previous_year_rating    1812
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
dtype: int64

In [36]:
test.previous_year_rating.fillna(0,inplace=True)

In [37]:
test.education.fillna(test.education.mode()[0],inplace=True)

In [38]:
test.gender.replace({'f':0,'m':1},inplace=True)

In [39]:
test.dtypes

department               object
education                object
gender                    int64
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
dtype: object

In [40]:
#LabelEncoder
test['department'] = le.fit_transform(test['department'])
test['education'] = le.fit_transform(test['education'])
test

department  education  gender  no_of_trainings  age  \
0               8          0       1                1   24   
1               2          0       0                1   31   
2               7          0       1                1   31   
3               5          0       0                3   31   
4               1          0       1                1   30   
...           ...        ...     ...              ...  ...   
23485           3          1       1                1   24   
23486           8          0       1                1   31   
23487           2          0       0                1   26   
23488           5          0       1                3   27   
23489           8          2       1                3   40   

       previous_year_rating  length_of_service  KPIs_met >80%  awards_won?  \
0                       0.0                  1              1            0   
1                       3.0                  5              0            0   
2                       1.0                  4              0            0   
3                       2.0                  9              0            0   
4                       4.0                  7              0            0   
...                     ...                ...            ...          ...   
23485                   3.0                  1              0            0   
23486                   3.0                  7              0            0   
23487                   4.0                  4              0            0   
23488                   0.0                  1              0            0   
23489                   5.0                  5              1            0   

       avg_training_score  
0                      77  
1                      51  
2                      47  
3                      65  
4                      61  
...                   ...  
23485                  61  
23486                  74  
23487                  50  
23488                  70  
23489                  89  

[23490 rows x 10 columns]

In [41]:
X_test=test.copy()

In [42]:
X_test.shape

(23490, 10)

In [43]:
X_test.columns

Index(['department', 'education', 'gender', 'no_of_trainings', 'age',
       'previous_year_rating', 'length_of_service', 'KPIs_met >80%',
       'awards_won?', 'avg_training_score'],
      dtype='object')

In [44]:
from sklearn.preprocessing import StandardScaler
X_test=scaler.transform(X_test)
print(X_test)

[[ 1.20797154 -0.62883817  0.65094726 ...  1.35687789 -0.15401776
   3.93474896]
 [-1.1862606  -0.62883817 -1.53622276 ... -0.73698599 -0.15401776
   1.99030582]
 [ 0.80893285 -0.62883817  0.65094726 ... -0.73698599 -0.15401776
   1.69116072]
 ...
 [-1.1862606  -0.62883817 -1.53622276 ... -0.73698599 -0.15401776
   1.91551954]
 [ 0.01085547 -0.62883817  0.65094726 ... -0.73698599 -0.15401776
   3.41124504]
 [ 1.20797154  1.61975831  0.65094726 ...  1.35687789 -0.15401776
   4.83218426]]


In [49]:
y_pred=model_DT.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [50]:
print(y_pred)

[1 1 1 ... 1 1 1]


In [51]:
test_copy['is_promoted']=pd.DataFrame(y_pred)

In [52]:
test_copy[['employee_id','is_promoted']]

employee_id  is_promoted
0             8724            1
1            74430            1
2            72255            1
3            38562            1
4            64486            1
...            ...          ...
23485        53478            1
23486        25600            1
23487        45409            1
23488         1186            1
23489         5973            1

[23490 rows x 2 columns]

In [55]:
selected_columns = test_copy[['employee_id', 'is_promoted']]
selected_columns.to_csv('HR_Analytics_solution.csv', index=False)